# Generated by Django 4.1.1 on 2023-01-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='admission',
        ),
    ]
