# Generated by Django 4.1.1 on 2023-01-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_rename_contact_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=14)),
                ('content', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
